[2024-02-02 11:16:36,048] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-02-02T11:16:34.086943+00:00 [queued]>
[2024-02-02 11:16:36,059] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-02-02T11:16:34.086943+00:00 [queued]>
[2024-02-02 11:16:36,060] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-02 11:16:36,060] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-02 11:16:36,060] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-02 11:16:36,074] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data_covid> on 2024-02-02 11:16:34.086943+00:00
[2024-02-02 11:16:36,078] {standard_task_runner.py:52} INFO - Started process 11464 to run task
[2024-02-02 11:16:36,082] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'get_data_covid', 'manual__2024-02-02T11:16:34.086943+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpa3b1cvuk', '--error-file', '/tmp/tmpg8ixwhz_']
[2024-02-02 11:16:36,083] {standard_task_runner.py:80} INFO - Job 356: Subtask get_data_covid
[2024-02-02 11:16:36,133] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.get_data_covid manual__2024-02-02T11:16:34.086943+00:00 [running]> on host c3bb523480bf
[2024-02-02 11:16:36,187] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=get_data_covid
AIRFLOW_CTX_EXECUTION_DATE=2024-02-02T11:16:34.086943+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-02T11:16:34.086943+00:00
[2024-02-02 11:16:39,082] {logging_mixin.py:115} INFO - Successfully install requests
[2024-02-02 11:16:39,147] {python.py:173} INFO - Done. Returned value was: get_data_covid
[2024-02-02 11:16:39,163] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=get_data_covid, execution_date=20240202T111634, start_date=20240202T111636, end_date=20240202T111639
[2024-02-02 11:16:39,197] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-02 11:16:39,233] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
