[2024-02-02 04:27:24,831] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-02T04:27:05.973041+00:00 [queued]>
[2024-02-02 04:27:24,858] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-02T04:27:05.973041+00:00 [queued]>
[2024-02-02 04:27:24,858] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-02 04:27:24,858] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-02 04:27:24,858] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-02 04:27:24,870] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): aggregate_dim_table> on 2024-02-02 04:27:05.973041+00:00
[2024-02-02 04:27:24,874] {standard_task_runner.py:52} INFO - Started process 1940 to run task
[2024-02-02 04:27:24,876] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'aggregate_dim_table', 'manual__2024-02-02T04:27:05.973041+00:00', '--job-id', '349', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpbggi5l0r', '--error-file', '/tmp/tmphfttemn1']
[2024-02-02 04:27:24,877] {standard_task_runner.py:80} INFO - Job 349: Subtask aggregate_dim_table
[2024-02-02 04:27:24,913] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-02T04:27:05.973041+00:00 [running]> on host c3bb523480bf
[2024-02-02 04:27:24,958] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=aggregate_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2024-02-02T04:27:05.973041+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-02T04:27:05.973041+00:00
[2024-02-02 04:27:27,363] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-02 04:27:29,696] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-02 04:27:31,990] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-02-02 04:27:34,351] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-02 04:27:34,411] {python.py:173} INFO - Done. Returned value was: insert dim table
[2024-02-02 04:27:34,428] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=aggregate_dim_table, execution_date=20240202T042705, start_date=20240202T042724, end_date=20240202T042734
[2024-02-02 04:27:34,440] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-02 04:27:34,463] {local_task_job.py:273} INFO - 5 downstream tasks scheduled from follow-on schedule check
