[2024-01-31 09:34:33,243] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T09:34:32.208080+00:00 [queued]>
[2024-01-31 09:34:33,248] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T09:34:32.208080+00:00 [queued]>
[2024-01-31 09:34:33,249] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 09:34:33,249] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-01-31 09:34:33,249] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 09:34:33,257] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_data_covid> on 2024-01-31 09:34:32.208080+00:00
[2024-01-31 09:34:33,260] {standard_task_runner.py:52} INFO - Started process 1250 to run task
[2024-01-31 09:34:33,262] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'get_data_covid', 'manual__2024-01-31T09:34:32.208080+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmplljnlc95', '--error-file', '/tmp/tmppcg4em57']
[2024-01-31 09:34:33,263] {standard_task_runner.py:80} INFO - Job 89: Subtask get_data_covid
[2024-01-31 09:34:33,302] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.get_data_covid manual__2024-01-31T09:34:32.208080+00:00 [running]> on host d99f9e65d396
[2024-01-31 09:34:33,349] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=get_data_covid
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T09:34:32.208080+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T09:34:32.208080+00:00
[2024-01-31 09:34:33,350] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-01-31 09:34:33,351] {subprocess.py:74} INFO - Running command: ['bash', '-c', '#!/bin/bash\n\nurl="http://103.150.197.96:5005/api/v1/rekapitulasi_v2/jabar/harian?level=kab"\noutput_file="data.txt"\n\ncurl -s "$url" >> "$output_file"']
[2024-01-31 09:34:33,358] {subprocess.py:85} INFO - Output:
[2024-01-31 09:34:33,406] {subprocess.py:96} INFO - Command exited with return code 0
[2024-01-31 09:34:33,427] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=get_data_covid, execution_date=20240131T093432, start_date=20240131T093433, end_date=20240131T093433
[2024-01-31 09:34:33,441] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-31 09:34:33,468] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
