[2024-01-31 14:42:20,219] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.import_file_to_mysql manual__2024-01-31T14:42:15.608617+00:00 [queued]>
[2024-01-31 14:42:20,225] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.import_file_to_mysql manual__2024-01-31T14:42:15.608617+00:00 [queued]>
[2024-01-31 14:42:20,225] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 14:42:20,225] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-01-31 14:42:20,226] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 14:42:20,233] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): import_file_to_mysql> on 2024-01-31 14:42:15.608617+00:00
[2024-01-31 14:42:20,237] {standard_task_runner.py:52} INFO - Started process 8038 to run task
[2024-01-31 14:42:20,239] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'import_file_to_mysql', 'manual__2024-01-31T14:42:15.608617+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp4uhjrfmd', '--error-file', '/tmp/tmp9nxkdgik']
[2024-01-31 14:42:20,240] {standard_task_runner.py:80} INFO - Job 154: Subtask import_file_to_mysql
[2024-01-31 14:42:20,275] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.import_file_to_mysql manual__2024-01-31T14:42:15.608617+00:00 [running]> on host d99f9e65d396
[2024-01-31 14:42:20,322] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=import_file_to_mysql
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T14:42:15.608617+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T14:42:15.608617+00:00
[2024-01-31 14:42:21,042] {logging_mixin.py:115} INFO - Error install json
[2024-01-31 14:42:23,883] {logging_mixin.py:115} INFO - Successfully install pandas
[2024-01-31 14:42:26,718] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-01-31 14:42:29,847] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-01-31 14:42:32,652] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-01-31 14:42:32,769] {python.py:173} INFO - Done. Returned value was: import to mysql
[2024-01-31 14:42:32,788] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=import_file_to_mysql, execution_date=20240131T144215, start_date=20240131T144220, end_date=20240131T144232
[2024-01-31 14:42:32,843] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-31 14:42:32,869] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
