[2024-01-31 15:42:56,601] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.import_file_to_mysql manual__2024-01-31T15:42:51.004140+00:00 [queued]>
[2024-01-31 15:42:56,608] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.import_file_to_mysql manual__2024-01-31T15:42:51.004140+00:00 [queued]>
[2024-01-31 15:42:56,608] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:42:56,609] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-01-31 15:42:56,609] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-31 15:42:56,618] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): import_file_to_mysql> on 2024-01-31 15:42:51.004140+00:00
[2024-01-31 15:42:56,621] {standard_task_runner.py:52} INFO - Started process 10705 to run task
[2024-01-31 15:42:56,624] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'import_file_to_mysql', 'manual__2024-01-31T15:42:51.004140+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpq9qfgdcw', '--error-file', '/tmp/tmp9wj2lcec']
[2024-01-31 15:42:56,625] {standard_task_runner.py:80} INFO - Job 206: Subtask import_file_to_mysql
[2024-01-31 15:42:56,665] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.import_file_to_mysql manual__2024-01-31T15:42:51.004140+00:00 [running]> on host d99f9e65d396
[2024-01-31 15:42:56,717] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=import_file_to_mysql
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T15:42:51.004140+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T15:42:51.004140+00:00
[2024-01-31 15:42:57,447] {logging_mixin.py:115} INFO - Error install json
[2024-01-31 15:43:00,294] {logging_mixin.py:115} INFO - Successfully install pandas
[2024-01-31 15:43:03,129] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-01-31 15:43:06,541] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-01-31 15:43:09,370] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-01-31 15:43:09,483] {python.py:173} INFO - Done. Returned value was: import to mysql
[2024-01-31 15:43:09,501] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=import_file_to_mysql, execution_date=20240131T154251, start_date=20240131T154256, end_date=20240131T154309
[2024-01-31 15:43:09,519] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-31 15:43:09,544] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
