[2024-02-01 11:48:48,338] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-01T11:48:47.339152+00:00 [queued]>
[2024-02-01 11:48:48,344] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-01T11:48:47.339152+00:00 [queued]>
[2024-02-01 11:48:48,344] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 11:48:48,344] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 11:48:48,344] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 11:48:48,352] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): aggregate_dim_table> on 2024-02-01 11:48:47.339152+00:00
[2024-02-01 11:48:48,356] {standard_task_runner.py:52} INFO - Started process 742 to run task
[2024-02-01 11:48:48,358] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'aggregate_dim_table', 'manual__2024-02-01T11:48:47.339152+00:00', '--job-id', '233', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpy918xw3_', '--error-file', '/tmp/tmp4el9e3uk']
[2024-02-01 11:48:48,359] {standard_task_runner.py:80} INFO - Job 233: Subtask aggregate_dim_table
[2024-02-01 11:48:48,396] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.aggregate_dim_table manual__2024-02-01T11:48:47.339152+00:00 [running]> on host 0cb2a3b23a40
[2024-02-01 11:48:48,449] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=aggregate_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T11:48:47.339152+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T11:48:47.339152+00:00
[2024-02-01 11:48:51,377] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 11:48:54,366] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 11:48:58,250] {logging_mixin.py:115} INFO - Successfully install pymysql
[2024-02-01 11:49:01,386] {logging_mixin.py:115} INFO - Successfully install sqlalchemy
[2024-02-01 11:49:03,524] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-02-01 11:49:03,527] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 742. PIDs of all processes in the group: [742]
[2024-02-01 11:49:03,527] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 742
[2024-02-01 11:49:03,527] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-01 11:49:03,555] {process_utils.py:75} INFO - Process psutil.Process(pid=742, status='terminated', exitcode=0, started='11:48:48') (742) terminated with exit code 0
