[2024-02-01 13:26:47,931] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-02-01T13:26:47.310511+00:00 [queued]>
[2024-02-01 13:26:47,938] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_postgresql.get_data_covid manual__2024-02-01T13:26:47.310511+00:00 [queued]>
[2024-02-01 13:26:47,938] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:26:47,939] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 13:26:47,939] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:26:47,948] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data_covid> on 2024-02-01 13:26:47.310511+00:00
[2024-02-01 13:26:47,952] {standard_task_runner.py:52} INFO - Started process 3190 to run task
[2024-02-01 13:26:47,956] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'get_data_covid', 'manual__2024-02-01T13:26:47.310511+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp3g17lelu', '--error-file', '/tmp/tmp01wu1fbl']
[2024-02-01 13:26:47,958] {standard_task_runner.py:80} INFO - Job 255: Subtask get_data_covid
[2024-02-01 13:26:48,006] {task_command.py:369} INFO - Running <TaskInstance: etl_postgresql.get_data_covid manual__2024-02-01T13:26:47.310511+00:00 [running]> on host 0cb2a3b23a40
[2024-02-01 13:26:48,073] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_postgresql
AIRFLOW_CTX_TASK_ID=get_data_covid
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T13:26:47.310511+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T13:26:47.310511+00:00
[2024-02-01 13:26:51,161] {logging_mixin.py:115} INFO - Successfully install requests
[2024-02-01 13:26:51,264] {python.py:173} INFO - Done. Returned value was: get_data_covid
[2024-02-01 13:26:51,282] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=get_data_covid, execution_date=20240201T132647, start_date=20240201T132647, end_date=20240201T132651
[2024-02-01 13:26:51,328] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 13:26:51,352] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
